#!/bin/bash -eu
USAGE="Usage: $0 [options] input_directory [more_input_directories]

Converts an entire Bruker dataset.
Output is Niftt by default.
Output directories will be created in current directory by default.
Will generate diffusion .bvec and .bval files for all DTI acquisitions.

Options (must go first):
    -e EXT : Use a different extension, e.g. .nrrd
    -l     : Keep localizers
    -p P   : Convert only the sequences that match pattern P
    -o DIR : Write output directories to this directory
    -q Q   : Submit jobs to the specified SGE queu
    -s     : Scale images by 10 for compatibility with SPM etc.
    -z     : Create zipped (.nii.gz) files
"

EXT=".nii"
LOCALIZERS=""
QUEUE=""
PATTERN="[0-9]*"
SCALE=""
OUT_DIR="$PWD"
VERBOSE=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while getopts "e:lo:p:q:sz" opt; do
    case $opt in
        e) EXT="$OPTARG";;
        l) LOCALIZERS="1";;
        o) OUT_DIR="$OPTARG";;
        p) PATTERN="$OPTARG";;
        q) QUEUE="-q $OPTARG"
           LOG_DIR="$OUT_DIR/nanbruker_logs/"
           mkdir -p $LOG_DIR
           ;;
        s) SCALE="--scale";;
        v) VERBOSE="-v";;
        z) EXT=".nii.gz";;
    esac
done

shift  $((OPTIND - 1))
if [ -z "${1-}" ]; then
    printf "$USAGE"
    exit 1
fi

# Loop over input directories
while test ${#} -gt 0; do
    SRC_DIR="$1"
    BASE_DIR="$( basename $SRC_DIR )"
    TGT_DIR="$OUT_DIR/$BASE_DIR"
    mkdir -p $TGT_DIR

    if [[ -n "$QUEUE" ]]; then
        INDEX_FILE="$LOG_DIR/$BASE_DIR.index"
        > $INDEX_FILE
    fi
    echo "Converting study $BASE_DIR"
    IMGS=$( ls "$SRC_DIR"/$PATTERN/pdata/*/2dseq | sort -n )
    echo "Found" $( wc -w <<< $IMGS ) "images to convert"
    for IMG in $IMGS; do
        ## Interrupted scans may end up with a 2dseq file with 0 bytes, annoyingly
        ## Or no visu_pars file
        IMG_DIR=$( dirname $IMG )
        VISU_PARS="$IMG_DIR/visu_pars"
        if [[ -s $IMG && -f $VISU_PARS ]]; then
            PROTOCOL=$( grep -A1 "\#\#\$VisuAcquisitionProtocol" $VISU_PARS | tail -n1 )
            if [[ -z "$LOCALIZERS" && $PROTOCOL == *"Localizer"* ]]; then
                if [[ -z "$QUEUE" ]]; then
                    echo "$IMG is a localizer, skipping"
                fi
            else
                if [[ -z "$QUEUE" ]]; then
                    echo "Converting $IMG"
                    nanconvert_bruker $VERBOSE $IMG $EXT $SCALE --prefix="$TGT_DIR"/\
                        --rename="VisuExperimentNumber" \
                        --rename="VisuProcessingNumber" \
                        --rename="VisuAcquisitionProtocol" \
                        --rename="VisuSeriesComment"
                else
                    echo $IMG >> $INDEX_FILE
                fi
            fi
        else
            echo "$IMG is empty, skipping."
        fi
    done

    if [[ -n "$QUEUE" ]]; then
        COUNT="$( wc -l < $INDEX_FILE )"
        if [[ "$COUNT" -gt 0 ]]; then
            echo "Found $COUNT images to convert"
            qsub -t 1:$COUNT -o ${LOG_DIR}/ -e ${LOG_DIR}/ -j y $QUEUE $SCRIPT_DIR/nanbruker_sge.qsub "$INDEX_FILE $EXT $TGT_DIR $SCALE"
        else
            echo "No files to convert in index file, not submitting a job"
        fi
    fi
    shift # Get next input directory
done
