#!/bin/bash -eu
USAGE="Usage: $0 [options] input_directory [more_input_directories]

Converts an entire GE DICOM dataset.
Output is Nifti by default.
Output directories will be created in current directory by default.

Options (must go first):
    -e EXT : Use a different extension, e.g. .nrrd
    -o DIR : Write output directories to this directory
    -z     : Create zipped (.nii.gz) files
"

EXT=".nii"
OUT_DIR="$PWD"
VERBOSE=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
while getopts "e:o:vz" opt; do
    case $opt in
        e) EXT="$OPTARG";;
        o) OUT_DIR="$OPTARG";;
        v) VERBOSE="-v";;
        z) EXT=".nii.gz";;
    esac
done

shift  $((OPTIND - 1))
if [ -z "${1-}" ]; then
    printf "$USAGE"
    exit 1
fi

# Loop over input directories
while test ${#} -gt 0; do
    SRC_DIR="$( cd $1 && pwd)"
    BASE_DIR="$( basename $SRC_DIR )"
    TGT_DIR="$OUT_DIR/$BASE_DIR"
    mkdir -p $TGT_DIR
    cd $TGT_DIR
    echo "Converting study $BASE_DIR"
    IMGS=$( ls -1 "$SRC_DIR"/*tar.bz2 | sort -n )
    echo "Found" $( wc -w <<< $IMGS ) "images to convert"
    for IMG in $IMGS; do
        STEM=$( basename $IMG .tar.bz2 )
        echo "Converting $STEM"
        cp $SRC_DIR/$STEM.tar.bz2 $STEM.tar.bz2
        bunzip2 $STEM.tar.bz2
        tar -xf $STEM.tar
        DICOMDIR="${STEM##*.}"
        nanconvert_dicom $DICOMDIR $EXT $VERBOSE
        rm -r $DICOMDIR $STEM.tar
    done
    cd $OUT_DIR
    shift # Get next input directory
done
